plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 34
    ndkVersion '27.0.12077973'

    defaultConfig {
        versionCode 63

        minSdkVersion 21
        targetSdkVersion 34

        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    flavorDimensions = ['machine']
    productFlavors {
        macPlus {
            dimension 'machine'
            applicationId 'com.hunterdavis.poolradmacmaps.plus'
            versionName '0.2.0'

            externalNativeBuild {
                ndkBuild {
                    arguments "NDK_FLAVOR=macPlus"
                }
            }
        }

        macII {
            dimension 'machine'
            applicationId 'com.hunterdavis.poolradmacmaps.ii'
            versionName '0.2.0'

            externalNativeBuild {
                ndkBuild {
                    arguments "NDK_FLAVOR=macII"
                }
            }
        }
    }

    splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'
            universalApk true
        }
    }

    externalNativeBuild {
        ndkBuild {
            path 'src/Android.mk'
        }
    }
    buildFeatures {
        viewBinding true
        buildConfig true
    }
    namespace 'name.osher.gil.minivmac'
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation 'com.android.support:multidex:1.0.3'

    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'

    implementation 'androidx.constraintlayout:constraintlayout:2.2.0'
    implementation 'androidx.navigation:navigation-fragment:2.8.7'
    implementation 'androidx.navigation:navigation-ui:2.8.7'
    implementation 'androidx.preference:preference:1.2.1'
}
